//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int AlertId { get; set; }
        public string Type { get; set; }
        public string Entity { get; set; }
        public Nullable<int> EntityId { get; set; }
        public string Severity { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ResolvedAt { get; set; }
        public Nullable<int> ResolvedBy { get; set; }
    }
}
