//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertRule
    {
        public int AlertRuleId { get; set; }
        public decimal MinFillComplianceThreshold { get; set; }
        public int LateDepartureMinutes { get; set; }
        public decimal CashVarianceThreshold { get; set; }
        public int IncidentSpikeThreshold { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
