//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingSeats = new HashSet<BookingSeat>();
            this.Payments = new HashSet<Payment>();
            this.SeatInventories = new HashSet<SeatInventory>();
        }
    
        public int BookingId { get; set; }
        public int DepartureId { get; set; }
        public int PassengerId { get; set; }
        public int SeatsCount { get; set; }
        public decimal FareEach { get; set; }
        public string PaymentMethod { get; set; }
        public string Status { get; set; }
        public string Pnr { get; set; }
        public byte[] QrBlob { get; set; }
        public Nullable<System.DateTime> ExpiresAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<decimal> ExtendedAmount { get; set; }
    
        public virtual Departure Departure { get; set; }
        public virtual Passenger Passenger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingSeat> BookingSeats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatInventory> SeatInventories { get; set; }
    }
}
