//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharterPayment
    {
        public int CharterPaymentId { get; set; }
        public int CharterId { get; set; }
        public decimal Amount { get; set; }
        public string StripePaymentIntentId { get; set; }
        public System.DateTime PaidAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Charter Charter { get; set; }
    }
}
