//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Charter()
        {
            this.CharterPassengers = new HashSet<CharterPassenger>();
            this.CharterPayments = new HashSet<CharterPayment>();
            this.CharterVehicles = new HashSet<CharterVehicle>();
        }
    
        public int CharterId { get; set; }
        public string Organizer { get; set; }
        public string Contact { get; set; }
        public System.DateTime Date { get; set; }
        public string PickupPlaceId { get; set; }
        public Nullable<decimal> PickupLat { get; set; }
        public Nullable<decimal> PickupLng { get; set; }
        public string DropPlaceId { get; set; }
        public Nullable<decimal> DropLat { get; set; }
        public Nullable<decimal> DropLng { get; set; }
        public int Pax { get; set; }
        public string Status { get; set; }
        public decimal QuoteAmount { get; set; }
        public bool DepositPaid { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int TaxiCount { get; set; }
        public bool ReturnTrip { get; set; }
        public string EventType { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public bool IsPaid { get; set; }
        public string StripePaymentIntentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharterPassenger> CharterPassengers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharterPayment> CharterPayments { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharterVehicle> CharterVehicles { get; set; }
    }
}
