//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharterPassenger
    {
        public int CharterPassengerId { get; set; }
        public int CharterId { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Charter Charter { get; set; }
    }
}
