//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departure()
        {
            this.Bookings = new HashSet<Booking>();
            this.CashupBags = new HashSet<CashupBag>();
            this.Expenses = new HashSet<Expens>();
            this.Floats = new HashSet<Float>();
            this.Incidents = new HashSet<Incident>();
            this.SeatInventories = new HashSet<SeatInventory>();
            this.Telemetries = new HashSet<Telemetry>();
            this.WaypointChecks = new HashSet<WaypointCheck>();
        }
    
        public int DepartureId { get; set; }
        public int RouteId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan PlannedTime { get; set; }
        public int VehicleId { get; set; }
        public int DriverId { get; set; }
        public int MinFill { get; set; }
        public string Status { get; set; }
        public bool ReadyChecklist_MinFill { get; set; }
        public bool ReadyChecklist_CashVerified { get; set; }
        public bool ReadyChecklist_FloatIssued { get; set; }
        public bool ReadyChecklist_VehicleCleared { get; set; }
        public bool ManagerOverrideReady { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashupBag> CashupBags { get; set; }
        public virtual User User { get; set; }
        public virtual Route Route { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expens> Expenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Float> Floats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatInventory> SeatInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telemetry> Telemetries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaypointCheck> WaypointChecks { get; set; }
    }
}
