//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpenseId { get; set; }
        public int DepartureId { get; set; }
        public string Type { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> ProofAttachmentId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual Departure Departure { get; set; }
    }
}
