//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxiRankDb3Entities2 : DbContext
    {
        public TaxiRankDb3Entities2()
            : base("name=TaxiRankDb3Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlertRule> AlertRules { get; set; }
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<Approval> Approvals { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingSeat> BookingSeats { get; set; }
        public virtual DbSet<CashupBag> CashupBags { get; set; }
        public virtual DbSet<CharterPassenger> CharterPassengers { get; set; }
        public virtual DbSet<CharterPayment> CharterPayments { get; set; }
        public virtual DbSet<Charter> Charters { get; set; }
        public virtual DbSet<CharterVehicle> CharterVehicles { get; set; }
        public virtual DbSet<Departure> Departures { get; set; }
        public virtual DbSet<DriverAssignment> DriverAssignments { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<FareRule> FareRules { get; set; }
        public virtual DbSet<Float> Floats { get; set; }
        public virtual DbSet<Incident> Incidents { get; set; }
        public virtual DbSet<MapsCache> MapsCaches { get; set; }
        public virtual DbSet<OwnerConfig> OwnerConfigs { get; set; }
        public virtual DbSet<Passenger> Passengers { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Rank> Ranks { get; set; }
        public virtual DbSet<ReportingArchive> ReportingArchives { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RouteWaypoint> RouteWaypoints { get; set; }
        public virtual DbSet<SeatInventory> SeatInventories { get; set; }
        public virtual DbSet<Settlement> Settlements { get; set; }
        public virtual DbSet<Telemetry> Telemetries { get; set; }
        public virtual DbSet<UserRank> UserRanks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VehicleDocument> VehicleDocuments { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<WaypointCheck> WaypointChecks { get; set; }
    }
}
