//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerConfig
    {
        public int OwnerConfigId { get; set; }
        public int OwnerId { get; set; }
        public decimal DriverSharePercent { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public decimal ManagerSharePercent { get; set; }
    
        public virtual User User { get; set; }
    }
}
