//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportingArchive
    {
        public int ArchiveId { get; set; }
        public string PeriodMonth { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
