//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.Departures = new HashSet<Departure>();
            this.FareRules = new HashSet<FareRule>();
            this.RouteWaypoints = new HashSet<RouteWaypoint>();
        }
    
        public int RouteId { get; set; }
        public int FromRankId { get; set; }
        public string ToName { get; set; }
        public string ToPlaceId { get; set; }
        public Nullable<decimal> ToLatitude { get; set; }
        public Nullable<decimal> ToLongitude { get; set; }
        public decimal DefaultFare { get; set; }
        public Nullable<decimal> DistanceKm { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departure> Departures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FareRule> FareRules { get; set; }
        public virtual Rank Rank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteWaypoint> RouteWaypoints { get; set; }
    }
}
