//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatInventory
    {
        public int SeatInventoryId { get; set; }
        public int DepartureId { get; set; }
        public int SeatNo { get; set; }
        public string Status { get; set; }
        public Nullable<int> BookingId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Departure Departure { get; set; }
    }
}
