//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settlement
    {
        public int SettlementId { get; set; }
        public int OwnerId { get; set; }
        public System.DateTime PeriodDay { get; set; }
        public decimal Gross { get; set; }
        public decimal Expenses { get; set; }
        public decimal DriverShare { get; set; }
        public decimal NetToOwner { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public decimal ManagerShare { get; set; }
    
        public virtual User User { get; set; }
    }
}
