//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telemetry
    {
        public int TelemetryId { get; set; }
        public int DepartureId { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public Nullable<decimal> SpeedKph { get; set; }
        public Nullable<int> Battery { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Departure Departure { get; set; }
    }
}
