//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDocument
    {
        public int VehicleDocumentId { get; set; }
        public int VehicleId { get; set; }
        public string DocType { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public System.DateTime UploadedAt { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
