//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiRank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaypointCheck
    {
        public int WaypointCheckId { get; set; }
        public int DepartureId { get; set; }
        public int RouteWaypointId { get; set; }
        public System.DateTime ReachedAt { get; set; }
    
        public virtual Departure Departure { get; set; }
        public virtual RouteWaypoint RouteWaypoint { get; set; }
    }
}
